# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Nasirodin
tagline:          'Personal page'
description:      'Nasirodin mazrooei '
url:              https://nasirodin.github.io/
baseurl:          /

author:
  name:           'Nasirodin Mazrooei'
  url:            https://twitter.com/ooddin
  avatar:         public/avatar.png
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
