# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Nasirodin
tagline:          'Personal page'
description:      'Nasirodin mazrooei '
url:              https://nasirodin.github.io/
baseurl:          /

author:
  name:           'Nasirodin Mazrooei'
  url:            https://twitter.com/ooddin

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
